- name: my 1st playbook
  hosts: all 
  vars:
    movie: "spiderman"
  tasks:
    - name: 1st task
      debug:
        msg: "Hello this {{movie}}"
    - name: 2st task
      debug:
        msg: "Hello this {{movie}}-2"
    